FROM python:3

RUN pip install click
RUN pip install pdflatex
RUN apt-get update && apt-get install -y --no-install-recommends texlive

COPY hw_2_1.py .
COPY hw_2_2.py .
COPY artifacts/ artifacts/

RUN pwd
RUN ls -lh

ENTRYPOINT ["python",  "hw_2_2.py"]
